class auxliares:
    TEXTO_FAMILIARES = 'SEM FAMILIARES INFORMADO'
    TEXTO_FALECIMENTO = 'DATA_FALECIMENTO'
    DATA_CAPTURA = 'SEM DATA CAPTURA'
    FALECIMENTO = "SEM DATA DE FALECIMENTO INFORMADA"
    A_NASCIMENTO = "DATA NÃO INFORMADA"
    IDADE = 0
    DATA_PARAO = '0000/00/00'
    DATA_C = '00/00/0000'
    TEXTO_P = "NÃO INFORMADO"
    # TEXTO_CONJUGE = "NÃO INFORMADO"