class auxliares:
    TEXTO_FAMILIARES = 'SEM FAMILIARES INFORMADO'
    TEXTO_FALECIMENTO = 'DATA_FALECIMENTO'
    DATA_CAPTURA = 'SEM DATA CAPTURA'
    FALECIMENTO = "SEM DATA DE FALECIMENTO INFORMADA"   
    A_NASCIMENTO = None
    A_IDADE = None
    IDADE = None
    CPF_LEN = 11
    DATA_PARAO = '0000-00-00'
    DATA_ENVIADA = '0000/00/00'
    DATA_C = '00/00/0000'
    TEXTO_P = "NÃO INFORMADO"
    TEXTO_CONJU = "CONJUGE"
    TEXTO_FILHO = "FILHOS",
    INFO_INSERT = "INSERT_NÃO_CONCLUIDO"
    # TEXTO_CONJUGE = "NÃO INFORMADO"